name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        shell: ['bash', 'zsh', 'csh', 'tcsh', 'ksh', 'fish']
    runs-on: ubuntu-latest
    env:
      TEST_USER: mb110
    steps:
      - name: Install shell
        run : |
          sudo apt update
          sudo apt install -y ${{ matrix.shell }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
      - name: Make user
        run: |
          sudo useradd -m $TEST_USER
      - name: Set shell
        run: |
          sudo chsh -s $(which ${{ matrix.shell }}) $TEST_USER
      - name: Run in user
        run: |
          su - $TEST_USER -c 'echo $PATH'
          su - $TEST_USER -c 'pip install "git+https://github.com/${{ github.repository }}"'
          su - $TEST_USER -c 'python -m puser'
          su - $TEST_USER -c 'echo $PATH'
